[2024-11-14T06:33:26.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T06:33:27.316+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_update.train_model manual__2024-11-14T06:33:19.478494+00:00 [queued]>
[2024-11-14T06:33:27.593+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_update.train_model manual__2024-11-14T06:33:19.478494+00:00 [queued]>
[2024-11-14T06:33:27.602+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-14T06:33:29.922+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpOperator): train_model> on 2024-11-14 06:33:19.478494+00:00
[2024-11-14T06:33:30.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'model_training_update', 'train_model', 'manual__2024-11-14T06:33:19.478494+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpcgb93lqb']
[2024-11-14T06:33:30.338+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask train_model
[2024-11-14T06:33:30.344+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=349) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T06:33:30.384+0000] {standard_task_runner.py:72} INFO - Started process 355 to run task
[2024-11-14T06:33:30.810+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-14T06:33:32.036+0000] {task_command.py:467} INFO - Running <TaskInstance: model_training_update.train_model manual__2024-11-14T06:33:19.478494+00:00 [running]> on host 4038974a3040
[2024-11-14T06:33:34.656+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_training_update' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T06:33:19.478494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T06:33:19.478494+00:00'
[2024-11-14T06:33:34.680+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T06:33:36.124+0000] {http.py:173} INFO - Calling HTTP method
[2024-11-14T06:33:36.399+0000] {job.py:229} INFO - Heartbeat recovered after 10.52 seconds
[2024-11-14T06:33:39.307+0000] {base.py:84} INFO - Retrieving connection 'fastapi'
[2024-11-14T06:33:40.104+0000] {base.py:84} INFO - Retrieving connection 'fastapi'
[2024-11-14T06:33:49.921+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T06:33:49.925+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=model_training_update, task_id=train_model, run_id=manual__2024-11-14T06:33:19.478494+00:00, execution_date=20241114T063319, start_date=20241114T063327, end_date=20241114T063349
[2024-11-14T06:33:50.048+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-14T06:33:50.190+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T06:33:50.197+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
